GET http://localhost:3000/api/movies

###
POST  http://localhost:3000/api/movies
content-type: application/json

{
    "title": "Toy story",
    "director": "Jhon Lasseter",
    "year":"1995",
    "rating":"8.8"
}